### ISSUE TITLE
Unable to find the template “modules\VideoHandler”.

### ISSUE THREAD

**Issue by yannick-yeboue-fm** [samhernandez/craft-shortcodes#1]
Hello, where do we store the “modules\VideoHandler.php” file?
I am getting the error Unable to find the template “modules\VideoHandler”.

I am also confused about this example below: Do I need config/app.php or config/shortcodes.php ??
My craft install does not have a config/app.php file
And is my-module supposed to be video ?

Enable the module in /config/app.php by uncommenting the commented lines that ship with Craft.

return [
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    'bootstrap' => ['my-module'],
];

Please, help

**Comment by samhernandez** [comment]
The documentation probably isn't clear. Sorry about that!

There are two ways to handle shortcodes:

1. Twig templates that you write
2. PHP classes that you write

The simplest way is to use Twig templates, and that's what I recommend. See the [Template Example](https://github.com/craftcms/craft/tree/master/modules) section for the full example.

I'd avoid PHP class handlers unless it became necessary for some reason. Otherwise, you can safely ignore the entire [PHP Class Handlers](https://github.com/samhernandez/craft-shortcodes#php-class-handlers) section.

If you really do need to use a PHP class, then that will require some knowledge around custom module and plugin development. I'm afraid that's outside the scope of help I can offer. [craftquest.io](https://craftquest.io/) is pretty awesome for that.

**Comment by yannick-yeboue-fm** [comment]
I figured it out using the modules. I didn't know I had to create a module and didnt have any boilerplate for that but I saw some examples online and was able to get it working now.
I need to make API calls via shortcodes to perform some computation, so the PHP Handler version is better for me.

Thanks for the quick reply

**Comment by samhernandez** [comment]
That's great! API calls via shortcodes sounds like an interesting use case.

Cheers 😀
